### ISSUE TITLE
pantheon-base/pantheon-files-9999: [dconf] failed to commit changes to dconf: The connection is closed

### ISSUE THREAD

**Issue by carlossura** [pimvullers/elementary#103]
Hello,

Now, I have installed pantheon-files and when trying to execute it, I get the following error:

[_LOG_LEVEL_FATAL 21:07:41.198119] [GLib] g_variant_ref: assertion 'value->ref_count > 0' failed
[_LOG_LEVEL_FATAL 21:07:41.198173] Files will not function properly.
[_LOG_LEVEL_WARN 21:07:41.201076] [dconf] failed to commit changes to dconf: The connection is closed

Full error: http://tny.cz/45fd358d

Please advise

**Comment by pimvullers** [comment]
Seems to be fixed on my system (either due to updated dependencies, or pantheon-files updates).
