### ISSUE TITLE
Pantheon-files force closes when I try to check a file/folder properties with root privileges.

### ISSUE THREAD

**Issue by MaddXav** [pimvullers/elementary#104]
Pantheon-files (from ElementaryOS Beta) force closes when I try to check file/folder properties with root privileges. I tried sudo, gksudo, su- and I keep getting the same issue. I do not have this problem when I have standar privileges though.

Here is the output from my terminal:

<blockquote> [_LOG_LEVEL_INFO 23:32:37.341125] Application.vala:155: Files version: 0.2.0
[_LOG_LEVEL_INFO 23:32:37.341209] Application.vala:157: Kernel version: 3.13.0-43-generic
[_LOG_LEVEL_INFO 23:32:37.388394] Application.vala:84: Report any issues/bugs you might find to http://bugs.launchpad.net/pantheon-files
[_LOG_LEVEL_WARN 23:32:37.391134] [libnotify] Failed to connect to proxy
[_LOG_LEVEL_FATAL 23:32:37.433508] string_contains: assertion 'self != NULL' failed
[_LOG_LEVEL_FATAL 23:32:37.433570] Files will not function properly.
[_LOG_LEVEL_FATAL 23:32:37.433604] string_contains: assertion 'self != NULL' failed
[_LOG_LEVEL_FATAL 23:32:37.433629] Files will not function properly.
[_LOG_LEVEL_FATAL 23:32:37.433662] string_contains: assertion 'self != NULL' failed
[_LOG_LEVEL_FATAL 23:32:37.433694] Files will not function properly.
[_LOG_LEVEL_FATAL 23:32:37.433725] string_contains: assertion 'self != NULL' failed
[_LOG_LEVEL_FATAL 23:32:37.433751] Files will not function properly.
[_LOG_LEVEL_FATAL 23:32:37.433782] string_contains: assertion 'self != NULL' failed
[_LOG_LEVEL_FATAL 23:32:37.433808] Files will not function properly.
[_LOG_LEVEL_FATAL 23:32:37.433839] string_contains: assertion 'self != NULL' failed
[_LOG_LEVEL_FATAL 23:32:37.433866] Files will not function properly.
[_LOG_LEVEL_WARN 23:32:37.508928] AbstractDirectoryView.vala:2721: Could not set file attributes - Setting attribute metadata::marlin-sort-column-id not supported
[_LOG_LEVEL_WARN 23:32:39.258013] AbstractDirectoryView.vala:2721: Could not set file attributes - Setting attribute metadata::marlin-sort-column-id not supported </blockquote>

Thanks for the assistance.

**Comment by pimvullers** [comment]
Please reopen if you have more information.
