### ISSUE TITLE
arm arch testing

### ISSUE THREAD

**Issue by lukashebda** [pimvullers/elementary#106]
I have armv7 and could do some ebuild testing. Would you consider that desirable?

**Comment by Maffblaster** [comment]
@lukashebda What's your current status on this? Did did you get everything working?

**Comment by lukashebda** [comment]
@Maffblaster: My current status is in no go state. Have allwinner A10 which is currently unusable due to updating linux-4.4 to mainstream (which at that time didn't include drm drivers). Will post something more if I will ever get the tablet running (main issue DTS).

**Comment by Maffblaster** [comment]
Realistically I'm not going to be able to get my Rpi 2 up and running anytime soon and it doesn't look like @lukashebda will be able to either. This issue has been opened for quite a while with no end it sight.

I will close this issue for now; if/when we get around to doing ARM testing again in the future someone can re-open a new task. It would be better to open a testing issue on a per-package basis if the package refuses to build while using a specific arch.
