### ISSUE TITLE
x11-wm/gala-0.1_p20141221 failed to fetch (404)

### ISSUE THREAD

**Issue by thorus90** [pimvullers/elementary#109]
Hi,

the link provided for the ebuild x11-wm/gala-0.1_p20141221 results in a 404 (not found).

I was not able to find the correct link.

Could you please fix that?

Thanks!

**Comment by Flex1911** [comment]
You can try my ebuild of gala https://github.com/Flex1911/qwin-overlay/tree/master/x11-wm/gala

**Comment by thorus90** [comment]
yeah thanks, with your ebuild it works.

Just for the record the ebuild just has to be edited so the link is:

SRC_URI="https://launchpad.net/~elementary-os/+archive/ubuntu/daily/+files/gala_0.1.0%7Er431%2Bpkg29%7Eubuntu14.10.1.tar.xz"

and the extraction process has to be altered accordingly.

Perhaps you can help with my starting problem of gala as well? I will open a new issue for that.

**Comment by thorus90** [comment]
I created a pull request, I hope I did that correctly(never did that, and my experiences with git are very few)

**Comment by pimvullers** [comment]
Thanks for the pull request. Only additional change that I made was also update the file name to reflect the changes, such that users with the previous version installed also get the update to the latest revision.

**Comment by brokenman** [comment]
This link above is now no longer valid. Pulling gala fails.
