### ISSUE TITLE
x11-wm/gala-0.1_p20150206 doesn't fetch

### ISSUE THREAD

**Issue by angryvincent** [pimvullers/elementary#112]
>>> Downloading 'http://distfiles.gentoo.org/distfiles/gala_0.1.0%7Er431%2Bpkg29%7Eubuntu14.10.1.tar.xz'
--2015-04-02 17:32:05--  http://distfiles.gentoo.org/distfiles/gala_0.1.0%7Er431%2Bpkg29%7Eubuntu14.10.1.tar.xz
Resolving distfiles.gentoo.org... 64.50.233.100, 64.50.236.52, 156.56.247.195, ...
Connecting to distfiles.gentoo.org|64.50.233.100|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-04-02 17:32:05 ERROR 404: Not Found.

>>> Downloading 'https://launchpad.net/~elementary-os/+archive/ubuntu/daily/+files/gala_0.1.0%7Er431%2Bpkg29%7Eubuntu14.10\
.1.tar.xz'
--2015-04-02 17:32:05--  https://launchpad.net/~elementary-os/+archive/ubuntu/daily/+files/gala_0.1.0%7Er431%2Bpkg29%7Eubu\
ntu14.10.1.tar.xz
Resolving launchpad.net... 91.189.89.222, 91.189.89.223
Connecting to launchpad.net|91.189.89.222|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-04-02 17:32:06 ERROR 404: Not Found.

!!! Couldn't download 'gala_0.1.0%7Er431%2Bpkg29%7Eubuntu14.10.1.tar.xz'. Aborting

**Comment by treeman1111** [comment]
I too am experiencing this problem. Thankfully, =gala-9999 still fetches and emerges correctly.

**Comment by pimvullers** [comment]
I'll try to provide an update this evening.
