### ISSUE TITLE
Stabalize SQLheavy for Noise-0.3.1

### ISSUE THREAD

**Issue by pimvullers** [pimvullers/elementary#113]
In order to have a stable noise, we also need a stable version of sqlheavy.

**Comment by Maffblaster** [comment]
Closing #140 can probably result in this issue being closed as well.

Looks like Noise version 0.4 (the loki release) doesn't rely on SQLHeavy anymore it appears to be no longer maintained. The only two other ebuilds that I could find referencing this in our repo are app-office/footnote (9999) and net-news/feedler (9999); both of are difficult for me to determine if they are maintained. I believe footnote is now known as[ pantheon-notes](https://launchpad.net/pantheon-notes)?

This is the only existing repository I could find for SQLHeavy that is even close to being maintained: https://github.com/nemequ/sqlheavy

What do you think, @pimvullers?

**Comment by pimvullers** [comment]
Hi, I just dropped sqlheavy > 0.1.1, and updated the 0.1.1 ebuild to have a proper SRC_URI again and stabilized it. This can be used for Noise-0.3.1, Feedler and Footnote. These last seem no longer maintained, but let's keep them for a bit. pantheon-notes seems to be a fresh implementation or at least a full rewrite of footnote (did not compile yet, so cannot compare the results, but sources differ a lot).
