### ISSUE TITLE
Does Maya live needs gtk+-3.16.0?

### ISSUE THREAD

**Issue by lukashebda** [pimvullers/elementary#114]
https://bpaste.net/show/ac09d1a48ee2

**Comment by pimvullers** [comment]
Nope, this is an issue with vala 0.28. When you use vala 0.26 it builds fine. 
I'll adjust the ebuild to set the maximum vala version to 0.26.
Op 13 apr. 2015 04:38 schreef lukashebda <notifications@github.com>:https://bpaste.net/show/ac09d1a48ee2
