### ISSUE TITLE
Gala ebuild needs fixing and some other updates....

### ISSUE THREAD

**Issue by BadMilo** [pimvullers/elementary#118]
Hi mate, on the gala ebuild  you need to change from  "mv "${WORKDIR}/gala-0.2.0~r460+pkg32~ubuntu0.3.1" "${S}""  to "mv "${WORKDIR}/gala-0.2.0~r464+pkg32~ubuntu0.3.1" "${S}"" otherwise it wont find the workdir. Also on some of the switchboard plug ebuilds there is the need to change the SRC_URI for example on switchboard-plug-power it has " SRC_URI="https://launchpad.net/${PN}/isis/${PV}/+download/${P}.tgz"" there is the need to change "isis" to "freya" Also i couldnt install elementary tweaks because it complaints about "missing package pantheon" im really lost in there...
Im more than happy to keep on reporting any bugs i find in my way.
Thank you for your work

**Comment by pimvullers** [comment]
Gala should be fixed now...

**Comment by pimvullers** [comment]
I'm currently quite busy, but I'll try to look into these issues when I have some more spare time.

**Comment by pimvullers** [comment]
Gala is fixed again
