### ISSUE TITLE
Non official apps with good integration with elementary

### ISSUE THREAD

**Issue by nado** [pimvullers/elementary#120]
Hi, do you accept non official app of the elementary project but with good integration in it ? Also should the apps be mature enough ? For example could we make an ebuild for https://launchpad.net/taxi (at least in -9999.ebuild)

Proposed additional theme https://github.com/horst3180/Arc-theme

**Comment by pimvullers** [comment]
Feel free to create a pull request.
Op 3 jun. 2015 3:29 PM schreef nado <notifications@github.com>:Hi, do you accept non official app of the elementary project but with good integration in it ? Also should the apps be mature enough ? For example could we make an ebuild for https://launchpad.net/taxi (at least in -9999.ebuild)

Proposed additional theme https://github.com/horst3180/Arc-theme

**Comment by pimvullers** [comment]
Taxi and Markmywords have been added. I'll accept any elementary related ebuilds, but will not add them myself.
