### ISSUE TITLE
Emerge sqlheavy fails

### ISSUE THREAD

**Issue by egordorichev** [pimvullers/elementary#123]
Hello! I'm trying to install noise. All looks good, but then I try to emerge sqlheavy emerge fails:
```
Calculating dependencies... done!

>>> Verifying ebuild manifests

>>> Emerging (1 of 3) dev-db/sqlheavy-0.2_p20121114::elementary
>>> Unpacking source...
Cloning into bare repository '/usr/portage/distfiles/egit-src/sqlheavy.git'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 * ERROR: dev-db/sqlheavy-0.2_p20121114::elementary failed (unpack phase):
 *   git-2_initial_clone: can't fetch from git://gitorious.org/sqlheavy/sqlheavy.git
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_unpack
 *   environment, line 3139:  Called git-2_src_unpack
 *   environment, line 2310:  Called git-2_fetch
 *   environment, line 2111:  Called git-2_initial_clone
 *   environment, line 2204:  Called die
 * The specific snippet of code:
 *       [[ -n ${EGIT_REPO_URI_SELECTED} ]] || die "${FUNCNAME}: can't fetch from ${EGIT_REPO_URI}"
 * 
 * If you need support, post the output of `emerge --info '=dev-db/sqlheavy-0.2_p20121114::elementary'`,
 * the complete build log and the output of `emerge -pqv '=dev-db/sqlheavy-0.2_p20121114::elementary'`.
 * The complete build log is located at '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/work'
 * S: '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/work/sqlheavy-0.2_p20121114'

>>> Failed to emerge dev-db/sqlheavy-0.2_p20121114, Log file:

>>>  '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/build.log'

 * Messages for package dev-db/sqlheavy-0.2_p20121114:

 * ERROR: dev-db/sqlheavy-0.2_p20121114::elementary failed (unpack phase):
 *   git-2_initial_clone: can't fetch from git://gitorious.org/sqlheavy/sqlheavy.git
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_unpack
 *   environment, line 3139:  Called git-2_src_unpack
 *   environment, line 2310:  Called git-2_fetch
 *   environment, line 2111:  Called git-2_initial_clone
 *   environment, line 2204:  Called die
 * The specific snippet of code:
 *       [[ -n ${EGIT_REPO_URI_SELECTED} ]] || die "${FUNCNAME}: can't fetch from ${EGIT_REPO_URI}"
 * 
 * If you need support, post the output of `emerge --info '=dev-db/sqlheavy-0.2_p20121114::elementary'`,
 * the complete build log and the output of `emerge -pqv '=dev-db/sqlheavy-0.2_p20121114::elementary'`.
 * The complete build log is located at '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/work'
 * S: '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/work/sqlheavy-0.2_p20121114'
```
How to fix this? Thanks.

**Comment by pimvullers** [comment]
It seems like the upstream git repository is unavailable. 
I'm on holiday now, without a laptop, so I cannot check. You might try to Google for another sqlheavy repo, and adjust the URL in the ebuild.
Op 14 jun. 2015 09:48 schreef Егор Доричев <notifications@github.com>:Hello! I'm trying to install noise. All looks good, but then I try to emerge sqlheavy emerge fails:

Calculating dependencies... done!

>>> Verifying ebuild manifests

>>> Emerging (1 of 3) dev-db/sqlheavy-0.2_p20121114::elementary
>>> Unpacking source...
Cloning into bare repository '/usr/portage/distfiles/egit-src/sqlheavy.git'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 * ERROR: dev-db/sqlheavy-0.2_p20121114::elementary failed (unpack phase):
 *   git-2_initial_clone: can't fetch from git://gitorious.org/sqlheavy/sqlheavy.git
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_unpack
 *   environment, line 3139:  Called git-2_src_unpack
 *   environment, line 2310:  Called git-2_fetch
 *   environment, line 2111:  Called git-2_initial_clone
 *   environment, line 2204:  Called die
 * The specific snippet of code:
 *       [[ -n ${EGIT_REPO_URI_SELECTED} ]] || die "${FUNCNAME}: can't fetch from ${EGIT_REPO_URI}"
 * 
 * If you need support, post the output of `emerge --info '=dev-db/sqlheavy-0.2_p20121114::elementary'`,
 * the complete build log and the output of `emerge -pqv '=dev-db/sqlheavy-0.2_p20121114::elementary'`.
 * The complete build log is located at '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/work'
 * S: '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/work/sqlheavy-0.2_p20121114'

>>> Failed to emerge dev-db/sqlheavy-0.2_p20121114, Log file:

>>>  '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/build.log'

 * Messages for package dev-db/sqlheavy-0.2_p20121114:

 * ERROR: dev-db/sqlheavy-0.2_p20121114::elementary failed (unpack phase):
 *   git-2_initial_clone: can't fetch from git://gitorious.org/sqlheavy/sqlheavy.git
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_unpack
 *   environment, line 3139:  Called git-2_src_unpack
 *   environment, line 2310:  Called git-2_fetch
 *   environment, line 2111:  Called git-2_initial_clone
 *   environment, line 2204:  Called die
 * The specific snippet of code:
 *       [[ -n ${EGIT_REPO_URI_SELECTED} ]] || die "${FUNCNAME}: can't fetch from ${EGIT_REPO_URI}"
 * 
 * If you need support, post the output of `emerge --info '=dev-db/sqlheavy-0.2_p20121114::elementary'`,
 * the complete build log and the output of `emerge -pqv '=dev-db/sqlheavy-0.2_p20121114::elementary'`.
 * The complete build log is located at '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/work'
 * S: '/var/tmp/portage/dev-db/sqlheavy-0.2_p20121114/work/sqlheavy-0.2_p20121114'


How to fix this? Thanks.

**Comment by pimvullers** [comment]
Could no reproduce, works fine here, probably the server was out at the moment you tried.
