### ISSUE TITLE
Emerge issues for Indicator-Datetime

### ISSUE THREAD

**Issue by tranquilitycal** [pimvullers/elementary#129]
```
[ 45%] Building CXX object src/CMakeFiles/indicatordatetimeservice.dir/locations.cpp.o
cd /var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build/src && /usr/bin/x86_64-pc-linux-gnu-g++  -DGETTEXT_PACKAGE=\"indicator-datetime\" -DGNOMELOCALEDIR=\"\" -DG_LOG_DOMAIN=\"Indicator-Datetime\" -DTIMEZONE_FILE=\"/etc/timezone\"  -DNDEBUG -march=native -O2 -pipe  -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/evolution-data-server -isystem /usr/include/nss -isystem /usr/include/nspr -isystem /usr/include/libsecret-1 -isystem /usr/include/libsoup-2.4 -isystem /usr/include/libxml2 -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libpng16 -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -I/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009/include -I/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build/include -I/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build/src -I/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009     -Wall -Wextra -pedantic -Wno-missing-field-initializers  -g -std=c++11 -o CMakeFiles/indicatordatetimeservice.dir/locations.cpp.o -c /var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009/src/locations.cpp
src/CMakeFiles/indicatordatetimeservice.dir/build.make:269: recipe for target 'src/CMakeFiles/indicatordatetimeservice.dir/engine-eds.cpp.o' failed
make[2]: *** [src/CMakeFiles/indicatordatetimeservice.dir/engine-eds.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build'
CMakeFiles/Makefile2:253: recipe for target 'src/CMakeFiles/indicatordatetimeservice.dir/all' failed
make[1]: *** [src/CMakeFiles/indicatordatetimeservice.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build'
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: x11-misc/indicator-datetime-13.10.0_p20141009::elementary failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=x11-misc/indicator-datetime-13.10.0_p20141009::elementary'`,
 * the complete build log and the output of `emerge -pqv '=x11-misc/indicator-datetime-13.10.0_p20141009::elementary'`.
 * The complete build log is located at '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/temp/environment'.
 * Working directory: '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build'
 * S: '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009'

>>> Failed to emerge x11-misc/indicator-datetime-13.10.0_p20141009, Log file:
```

Not sure why, I had just added the Elementary overlay and emerged pantheon-shell and it always gets stuck at this.

**Comment by txl263** [comment]
[ 62%] Building CXX object src/CMakeFiles/indicatordatetimeservice.dir/planner-snooze.cpp.o
cd /var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build/src && /usr/lib/ccache/bin/i686-pc-linux-gnu-g++  -DGETTEXT_PACKAGE=\"indicator-datetime\" -DGNOMELOCALEDIR=\"\" -DG_LOG_DOMAIN=\"Indicator-Datetime\" -DTIMEZONE_FILE=\"/etc/timezone\"  -DNDEBUG -O2 -march=i686 -pipe  -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/evolution-data-server -isystem /usr/include/nss -isystem /usr/include/nspr -isystem /usr/include/libsecret-1 -isystem /usr/include/libsoup-2.4 -isystem /usr/include/libxml2 -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libpng16 -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -I/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009/include -I/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build/include -I/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build/src -I/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009     -Wall -Wextra -pedantic -Wno-missing-field-initializers  -g -std=c++11 -o CMakeFiles/indicatordatetimeservice.dir/planner-snooze.cpp.o -c /var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009/src/planner-snooze.cpp
/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009/src/engine-eds.cpp: In static member function ‘static void unity::indicator::datetime::EdsEngine::Impl::on_source_enabled(ESourceRegistry*, ESource*, gpointer)’:
/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009/src/engine-eds.cpp:242:39: error: invalid conversion from ‘GCancellable* {aka _GCancellable*}’ to ‘guint32 {aka unsigned int}’ [-fpermissive]
                                  gself);
                                       ^
/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009/src/engine-eds.cpp:242:39: error: cannot convert ‘void (*)(GObject*, GAsyncResult*, gpointer) {aka void (*)(_GObject*, _GAsyncResult*, void*)}’ to ‘GCancellable* {aka _GCancellable*}’ for argument ‘4’ to ‘void e_cal_client_connect(ESource*, ECalClientSourceType, guint32, GCancellable*, GAsyncReadyCallback, gpointer)’
src/CMakeFiles/indicatordatetimeservice.dir/build.make:268: recipe for target 'src/CMakeFiles/indicatordatetimeservice.dir/engine-eds.cpp.o' failed
make[2]: *** [src/CMakeFiles/indicatordatetimeservice.dir/engine-eds.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build'
CMakeFiles/Makefile2:253: recipe for target 'src/CMakeFiles/indicatordatetimeservice.dir/all' failed
make[1]: *** [src/CMakeFiles/indicatordatetimeservice.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build'
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
 * ERROR: x11-misc/indicator-datetime-13.10.0_p20141009::elementary failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=x11-misc/indicator-datetime-13.10.0_p20141009::elementary'`,
 * the complete build log and the output of `emerge -pqv '=x11-misc/indicator-datetime-13.10.0_p20141009::elementary'`.
 * The complete build log is located at '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/temp/environment'.
 * Working directory: '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build'
 * S: '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009'

>>> Failed to emerge x11-misc/indicator-datetime-13.10.0_p20141009, Log file:

>>>  '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/temp/build.log'

 * Messages for package x11-misc/indicator-datetime-13.10.0_p20141009:

 * ERROR: x11-misc/indicator-datetime-13.10.0_p20141009::elementary failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=x11-misc/indicator-datetime-13.10.0_p20141009::elementary'`,
 * the complete build log and the output of `emerge -pqv '=x11-misc/indicator-datetime-13.10.0_p20141009::elementary'`.
 * The complete build log is located at '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/temp/environment'.
 * Working directory: '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0_p20141009_build'
 * S: '/var/tmp/portage/x11-misc/indicator-datetime-13.10.0_p20141009/work/indicator-datetime-13.10.0+14.10.20141009'

**Comment by txl263** [comment]
Portage 2.2.18 (python 2.7.10-final-0, default/linux/x86/13.0, gcc-4.8.3, glibc-2.20-r2, 3.18.7-gentoo i686)
=================================================================
System uname: Linux-3.18.7-gentoo-i686-Intel-R-_Core-TM-_i5-4430_CPU_@_3.00GHz-with-gentoo-2.2
KiB Mem:     1032704 total,    525248 free
KiB Swap:     996024 total,    987752 free
Timestamp of repository gentoo: Sun, 05 Jul 2015 20:00:01 +0000
sh bash 4.3_p39
ld GNU ld (Gentoo 2.25 p1.2) 2.25
ccache version 3.2.1 [enabled]
app-shells/bash:          4.3_p39::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10::gentoo, 3.3.5-r1::gentoo
dev-util/ccache:          3.2.1-r1::gentoo
dev-util/cmake:           3.1.0::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.17::gentoo
sys-apps/sandbox:         2.6-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r1::gentoo
sys-devel/automake:       1.13.4::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25-r1::gentoo
sys-devel/gcc:            4.8.3::gentoo, 4.9.3::gentoo
sys-devel/gcc-config:     1.8::gentoo
sys-devel/libtool:        2.4.6-r1::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 3.19::gentoo (virtual/os-headers)
sys-libs/glibc:           2.20-r2::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

elementary
    location: /var/lib/layman/elementary
    sync-type: laymansync
    sync-uri: git://github.com/pimvullers/elementary.git
    masters: gentoo
    priority: 50

gentoo-zh
    location: /var/lib/layman/gentoo-zh
    sync-type: laymansync
    sync-uri: git://github.com/microcai/gentoo-zh.git
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="x86 ~x86"
ACCEPT_LICENSE="* -@EULA"
CBUILD="i686-pc-linux-gnu"
CFLAGS="-O2 -march=i686 -pipe"
CHOST="i686-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php5.6/ext-active/ /etc/php/cgi-php5.6/ext-active/ /etc/php/cli-php5.6/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -march=i686 -pipe"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -march=i686 -pipe"
FEATURES="assume-digests binpkg-logs ccache config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
FFLAGS="-O2 -march=i686 -pipe"
GENTOO_MIRRORS="http://mirrors.163.com/gentoo/"
LANG="zh_CN.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j3"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
USE="X acl alsa apache apache2 berkdb bindist bzip2 cjk cli cracklib crypt cxx db dot dri dubs fortran gd gdbm iconv imap jpeg libwww maildir mmx modules mysql ncurses nls nptl nptlonly opengl openmp openssl pam pcre php readline ruby22 sasl session snmp sockets sse sse2 ssl tcpd threads unicode vhosts x86 xml zlib" ABI_X86="32" APACHE2_MODULES="unixd filter deflate rewrite cache file_cache cache_disk access_compat authn_alias authn_core authz_core socache_shmcb actions alias auth_basic authn_alias authn_anon authn_dbm version authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers \ include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev keyboard mouse vmmouse" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="zh_CN" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_3" RUBY_TARGETS="ruby19 ruby20" USERLAND="GNU" VIDEO_CARDS="vesa vga fbdev" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CPPFLAGS, CTARGET, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

**Comment by pimvullers** [comment]
Could you please check your version of gnome-extra/evolution-data-server?
My guess is it's 3.16.4_pre. This update has broken the build. I'll adjust the dependencies for now, untill a fix has been provided by upstream

**Comment by txl263** [comment]
Thank you!
After update gnome-extra/evolution-data-server down to 3.12.11, the Indicator-Dateline emerge success.
