### ISSUE TITLE
x11-themes/elementary-icon-theme-4.0_p1520

### ISSUE THREAD

**Issue by flower1024** [pimvullers/elementary#141]
* bzr pull start -->
 *    repository: lp:elementaryicons
bzr: ERROR: Not a branch: "/usr/portage/distfiles/bzr-src/elementary-icon-theme/.bzr/branch/": location is a repository.

emerge --info '=x11-themes/elementary-icon-theme-4.0_p1520::elementary'
Portage 2.2.20.1 (python 3.4.3-final-0, default/linux/amd64/13.0/desktop/gnome/systemd, gcc-4.9.3, glibc-2.21-r1, 4.0.9-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.0.9-gentoo-x86_64-Intel-R-_Core-TM-_i7-3517U_CPU_@_1.90GHz-with-gentoo-2.2
Timestamp of repository gentoo: Sat, 31 Oct 2015 09:30:01 +0000
sh bash 4.3_p39
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p39::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.10::gentoo, 3.4.3::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.17::gentoo
sys-apps/sandbox:         2.6-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.10.3-r1::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 3.18::gentoo (virtual/os-headers)
sys-libs/glibc:           2.21-r1::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

elementary
    location: /var/lib/layman/elementary
    masters: gentoo
    priority: 0

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -march=native -fomit-frame-pointer"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -pipe -march=native -fomit-frame-pointer"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="de_DE.iso885915@euro"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 apm bash-completion berkdb bluray branding bzip2 cairo cdda cddb cdparanoia cdr cli client colord cracklib crypt css curl cxx dbus dga directfb dri dts dvd dvdr eds emboss encode evo exif fam fbcon ffmpeg firefox flac fortran ftp gdbm gif gimp git glamor glut gnome gnome-keyring gnome-online-accounts gnutls gpm gstreamer gtk gtk3 gudev gzip hddtemp iconv icu imagemagick imap inotify introspection ipv6 jpeg jpeg2k lame latex lcms ldap libnotify libsecret lm_sensors lock mad mms mmx mmxext mng modules mono mozilla mp3 mp4 mpeg mpi multilib nautilus ncurses nls nntp nocd nptl offensive ogg opengl openmp pam pango pantheon pcre pdf png policykit polkit ppds prelink pulseaudio pyhon qt3support readline rss samba sdl seccomp session smp sound spell spice sse sse2 sse3 sse4_1 sse4_2 ssl ssse3 startup-notification svg systemd tcpd theora threads tidy tiff tracker truetype udev udisks unicode upower usb vaapi vcd vdpau vim-syntax vorbis webkit wmf wxwidgets x264 xa xattr xcb xcomposite xinerama xml xpm xv xvid zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="de en" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="fbdev glint intel mach64 mga nouveau nv r128 radeon savage sis tdfx trident vesa via vmware dummy v4l" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, MAKEOPTS, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

**Comment by flower1024** [comment]
started from scratch with way less use flags and it worked.
not sure why though ;-)

**Comment by txl263** [comment]
>>> Emerging (2 of 2) x11-themes/elementary-icon-theme-4.0_p1520::elementary
>>> Unpacking source...
 * bzr pull start -->
 *    repository: lp:elementaryicons
bzr: ERROR: Not a branch: "/usr/portage/distfiles/bzr-src/elementary-icon-theme/.bzr/branch/": location is a repository.
 * ERROR: x11-themes/elementary-icon-theme-4.0_p1520::elementary failed (unpack phase):
 *   bzr.eclass: can't pull from lp:elementaryicons
 * 
 * Call stack:
 *     ebuild.sh, line  133:  Called src_unpack
 *   environment, line 2450:  Called bzr_src_unpack
 *   environment, line  456:  Called bzr_fetch
 *   environment, line  425:  Called bzr_update 'lp:elementaryicons' '/usr/portage/distfiles/bzr-src/elementary-icon-theme'
 *   environment, line  473:  Called die
 * The specific snippet of code:
 *           ${EBZR_UPDATE_CMD} ${EBZR_OPTIONS} "${repo_uri}" || die "${EBZR}: can't pull from ${repo_uri}";
