### ISSUE TITLE
Pantheon meta package (Elementary's default package list)

### ISSUE THREAD

**Issue by Maffblaster** [pimvullers/elementary#147]
Hi, I was wondering what happened to the Pantheon meta package (which was at one time called pantheon-base/pantheon as referring to on the Gentoo wiki)? Such a package would install all the packages and dependencies for the equivalent of an Elementary OS DE install on Gentoo. :)

Here is where I saw the pantheon-base/pantheon package: https://wiki.gentoo.org/wiki/Pantheon

I'd be happy to help you test Pantheon on Gentoo. I'd like to get the look and feel very similar to Elementary OS. I enjoy it a lot. Let me know what I can do to help. Thanks!

**Comment by pimvullers** [comment]
Hi, I dropped pantheon meta package since it was quite outdated. pantheon-base/pantheon-shell is kind of the new meta package, it installs the pantheon shell which gives the elementary OS DE. The main difference is that it does not include additional applications like files, terminal etc.

**Comment by Maffblaster** [comment]
Well, needless to say, I used Elementary OS this weekend and I really enjoyed it. Perhaps in the README you could put a an emerge command that would match the package list of the currently available version of Elementary OS DE and perhaps update the Gentoo wiki with current instructions on how to install a built-from-source version of Elementary OS DE on Gentoo? :)

**Comment by lyssdod** [comment]
I highly support this. Just emerged pantheon-shell & got no window manager (headerless windows) and no cursor

**Comment by Maffblaster** [comment]
@pimvullers I'd be happy to help maintain this overlay and QA the packages. I could also update the Elementary article on the Gentoo wiki as well. Don't feel like you have to do it all by yourself! :smiley: 

Do you hang out in any Freenode IRC channels?

**Comment by pimvullers** [comment]
@Maffblaster I'm no longer active on IRC. I started the Gentoo elementary overlay when I was a PhD student, when I had more time available, or could easily fix things under working hours.
Now I'm more in maintenance mode in just keeping it up, with a minimal effort. So any help is appreciated :)

**Comment by Maffblaster** [comment]
@pimvullers Can you make me part of the project on here please? Write access?

**Comment by Maffblaster** [comment]
@pimvullers Either give me write access here or, under your permission, I can clone this overlay into to the official @Gentoo project and start managing it there. Your history with this will be preserved...

**Comment by Maffblaster** [comment]
Over the next new weeks, as time allows, I'll be working on getting Pantheon a meta package that will pull in the whole DE. Thanks, @pimvullers!
