### ISSUE TITLE
Does it stop development？

### ISSUE THREAD

**Issue by ykla** [pimvullers/elementary#166]
I love this desktop very much.

**Comment by pimvullers** [comment]
Development of the Pantheon Desktop Environment is done by the elementary team (https://elementary.io/). I only take care of the packaging for Gentoo. This repository is quite up-to-date, but I don;t have time anymore to actively search for new elementary related apps and add them. I'm more in a maintenance mode for the core apps and libs.

If you want to add additional packages, feel free to create a pull request.
