### ISSUE TITLE
elementary OS or social-engineer-toolkit bug?

### ISSUE THREAD

**Issue by Ghostboy-287** [pimvullers/elementary#179]
Hello

I wanted to install social-engineer-toolkit but after following [the steps one by one correctly ](https://github.com/trustedsec/social-engineer-toolkit/#installation), I come across a small problem:
 when I want to launch (start) directly the script (which is in the path folder) using `set` command => i got like an `echo` of a [bash script](https://dpaste.de/VgWE)

alternative info:
```
$ whereis set
set: /usr/share/man/man1/set.1posix.gz

```
ps: 

- social-engineer-toolkit works fine when i enter to its folder and using `$ python setoolkit`

- normally after installing social-engineer-toolkit we can launch it from anywhere using `set` command 

[social-engineer-toolkit issue](https://github.com/trustedsec/social-engineer-toolkit/issues/461)

**Comment by pimvullers** [comment]
Hi Ghostboy, this is just the elementary OS overlay for Gentoo, that is packaging the elementary OS packages for Gentoo Linux. I'm not affiliated with elementaryOS. Please check https://elementary.io/support for support options.
