### ISSUE TITLE
Wifi button & wifi panel menu

### ISSUE THREAD

**Issue by Ghostboy-287** [pimvullers/elementary#182]
Hello,
My Laptops has wifi button to disable or enable wifi.

with Elementary Os the button works when i would like to disable wifi but when i click again to enable it, it doesn't work (it don't enable the wifi)

and when i click on the wifi icon on the top right corner the `wifi` and `wired` are **blank (gray)** (cant click on them , **cant check** them to enable wifi or ethernet) and i have to enter to network setting to enable them

**Comment by pimvullers** [comment]
Hi Ghostboy, as mentioned in your previous issue, please check https://elementary.io/support or https://github.com/elementary for support from the elementary theme. This project is only focussed on packaging the elementary apps for  Gentoo Linux.
