### ISSUE TITLE
Dependency issue with dev-libs/libxslt

### ISSUE THREAD

**Issue by christoph-heiss** [pimvullers/elementary#204]
I'm trying to install Pantheon on an fully up-to-date (as of writing this) `~amd64` Gentoo installation on an Intel Broadwell system.

Pretty bog-standard `make.conf`: 
```
ACCEPT_KEYWORDS="~amd64"
USE="networkmanager policykit zstd http2 nghttp3 brotli vim-syntax -nls -smartcard"
```

Repository was added via `eselect repository enable elementary`.

Running `emerge -avt pantheon-base/pantheon-shell` then returns the following:
```
emerge: there are no ebuilds built with USE flags to satisfy "dev-libs/libxslt[python]".
!!! One of the following packages is required to complete your request:
- dev-libs/libxslt-1.1.34-r1::gentoo (Missing IUSE: python)
(dependency required by "x11-libs/bamf-0.5.4::elementary" [ebuild])
(dependency required by "x11-wm/gala-3.3.2::elementary" [ebuild])
(dependency required by "pantheon-base/pantheon-shell-5.0.3::elementary" [ebuild])
(dependency required by "pantheon-base/pantheon-shell" [argument])
```
The `python` IUSE flag apparently went away with `dev-libs/libxslt-1.1.34-r1`, but is still present for `dev-libs/libxslt-1.1.34` according to the .ebuild files.

I'm pretty new to Gentoo and tried some fiddeling around to maybe fix that issue, but to no avail. 
If you guys could give me some adivce/tips on how to fix that I'd be willing to test it and create a pull request.

Thanks!

**Comment by Dirli** [comment]
you can take a look here
https://github.com/Dirli/gpde/tree/master/x11-libs/bamf

**Comment by christoph-heiss** [comment]
Thanks @Dirli! That helped a lot, I could resolve the issues using your repo as an reference!
