### ISSUE TITLE
Gala fails to compile: Run-time dependency libmutter-2 not found

### ISSUE THREAD

**Issue by Malternative3772** [pimvullers/elementary#209]
[emerge --info output.txt](https://github.com/pimvullers/elementary/files/6720434/emerge.--info.output.txt)
[build.log](https://github.com/pimvullers/elementary/files/6720438/build.log)

**Comment by Dirli** [comment]
Please specify what version you have mutter?
I'll assume that you have mutter-40. It does not yet have support from the gala developers, need to specify an upper bound in ebuild.
You need to look for mutter-7 (3.38), this is the latest officially supported one. As soon as either the developers or I manage to build a gala with mutter-40, I will let you know

**Comment by Malternative3772** [comment]
Got it. Tanks for your help:)
