### ISSUE TITLE
Update everything to 6.0 versions

### ISSUE THREAD

**Issue by Titaniumtown** [pimvullers/elementary#211]
Since Elementary OS 6.0 released, will these packages be updated also?

**Comment by pimvullers** [comment]
I'll give it a try. But my first step will be to install OS 6 itself. Op 16 aug. 2021 23:08 schreef Simon Gardling ***@***.***>:
Since Elementary OS 6.0 released, will these packages be updated also?

**Comment by pimvullers** [comment]
work has started on eos6 branch.

**Comment by Titaniumtown** [comment]
> work has started on eos6 branch.

Thanks, keep me posted! ❤️

**Comment by pimvullers** [comment]
> contract for archives has not been added, although it is available in the upstream

I see it in your overlay/github, but not in official elementary one. So what do you mean by upstream here?

**Comment by Dirli** [comment]
https://github.com/elementary/file-roller-contract

**Comment by Dirli** [comment]
previously, EOS was patched with file-roller, but this was not suitable for other distributions, now they have made a separate package

**Comment by pimvullers** [comment]
OK, will look into that at some later moment.

I will most likely merge to master at end of this week.

**Comment by Titaniumtown** [comment]
Any progress?

**Comment by pimvullers** [comment]
As indicated above eos6 branch should be functional. I have been quite busy at work and have actually been using my eos6 install instead of gentoo most of the time. So have not had a chance to include the October package updates and merge to master.
That said, nothing should prevent you from using the branch.

**Comment by Titaniumtown** [comment]
ah ok.

**Comment by pimvullers** [comment]
eos6 branch delivered to master
