### ISSUE TITLE
dev-libs/appstream

### ISSUE THREAD

**Issue by NelvinBHV** [pimvullers/elementary#212]
The ebuild from dev-libs/appstream should be now the version dev-libs/appstream-0.14.4-r1. In the main gentoo repository is now the same version without vala support. This breaks pantheon-base/applications-menu. The PATCHES-line in this ebuild should also be removed, because the patch is not availble in the eos6 repository.

**Comment by joostruis** [comment]
Sorry to comment on this old closed issue here, but I brought the matter up again here: https://bugs.gentoo.org/733768
