### ISSUE TITLE
Gala Unable to Compile

### ISSUE THREAD

**Issue by RetronEletron** [pimvullers/elementary#214]
Log=https://pastebin.com/HPxfJ6EJ
Make.conf=https://pastebin.com/hjWQgxCb
Libmutter seems to be the main issue and i cant find any package nor solution related to it.

EDIT: This seems to be an issue overall not just with this specific overlay package

**Comment by gebau00a** [comment]
Dumb question maybe, but I cannot find the solution myself.
I sync my repos via eselect repository, so I could not jump on the eos6 branch.
So I tried via the repo file elementary.conf, but also this pulls in master only.

How to automatically sync the eos6 branch?

**Comment by pimvullers** [comment]
Ah yes, eselect indeed uses a mirror and not this repository directly. One option would be to do a manual clone. Op 16 nov. 2021 15:50 schreef gebau00a ***@***.***>:
Dumb question maybe, but I cannot find the solution myself.
I sync my repos via eselect repository, so I could not jump on the eos6 branch.
So I tried via the repo file elementary.conf, but also this pulls in master only.
How to automatically sync the eos6 branch?

**Comment by gebau00a** [comment]
Was even using the elementary.conf repo file.
I now followed your advise, deleted my elementary repo folder and cloned new via
`git clone https://github.com/pimvullers/elementary.git -b eos6`
This can now be updated also via emaint sync

Thanks for the suggestion

**Comment by pimvullers** [comment]
I just delivered the eos6 branch to master. Gala was updated to latest version.
