### ISSUE TITLE
pantheon-base/switchboard: meson error: libunity

### ISSUE THREAD

**Issue by gebau00a** [pimvullers/elementary#215]
When compiling switchboard from the eos6 branch, the configure process breaks down with
`meson.build:1:0: ERROR: Unknown options: "libunity"`

[https://gpo.zugaina.org/dev-libs/libunity/](https://gpo.zugaina.org/dev-libs/libunity/) shows there's a package libunity, but do I need to add this overlay now as well?

**Comment by pimvullers** [comment]
Can you please provide more details, like emerge log/output? Just built fine on my side.

**Comment by pimvullers** [comment]
More details were provided in #216, issue should be resolved now.
