### ISSUE TITLE
pantheon-mail fails to compile

### ISSUE THREAD

**Issue by b0ywearngtights** [pimvullers/elementary#217]
I'm facing 2 errors while trying to compile pantheon-mail.
First missing dev-libs/folks dependencie in the ebuild.
and then :  
```
error: Package `libedataserverui-1.2' not found in specified Vala API directories or GObject-Introspection GIR directories  
error: Package `libedataserver-1.2' not found in specified Vala API directories or GObject-Introspection GIR directories  
```

(does folks need the eds flag and evolution-data-server the vala flag ?)

**Comment by pimvullers** [comment]
Added missing dependencies, and the last error was most likely caused by missing vala flag on evolution-data-server.
Please let me know whether the commit above fixes the problem, or what the latest error is.

**Comment by b0ywearngtights** [comment]
Now everything works as expected thx!
