### ISSUE TITLE
pantheon-base/pantheon-shell-6.0.0 failing to build

### ISSUE THREAD

**Issue by InvisibleRasta** [pimvullers/elementary#219]
* Package:    pantheon-base/pantheon-shell-6.0.0
 * Repository: elementary
 * Maintainer: elementary@vullersmail.nl maffblaster@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking pantheon-shell-6.0.0.tar.gz to /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work
>>> Source unpacked in /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work
>>> Preparing source in /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/session-settings-6.0.0 ...
 * Applying 6.0.0-fix_access_deps.patch ...                                                                                  [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/session-settings-6.0.0 ...
meson setup --libdir lib64 --localstatedir /var/lib --prefix /usr --sysconfdir /etc --wrap-mode nodownload --build.pkg-config-path /usr/share/pkgconfig --pkg-config-path /usr/share/pkgconfig --native-file /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/temp/meson.x86_64-pc-linux-gnu.amd64.ini --buildtype plain -Ddetect-program-prefixes=false -Daccessibility=false /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/session-settings-6.0.0 /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/pantheon-shell-6.0.0-build
The Meson build system
Version: 0.60.3
Source dir: /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/session-settings-6.0.0
Build dir: /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/pantheon-shell-6.0.0-build
Build type: native build
Project name: elementary-session-settings
Project version: 5.0.3
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/x86_64-pc-linux-gnu-pkg-config (1.8.0)
Run-time dependency gnome-settings-daemon found: YES 41.0
Configuring pantheon.session using configuration
Program desktop-file-install found: YES (/usr/bin/desktop-file-install)
session/meson.build:153: WARNING: Custom target input '['/etc/xdg/autostart/gnome-keyring-pkcs11.desktop']' can't be converted to File object(s).
This will become a hard error in the future.
session/meson.build:153: WARNING: Custom target input '['/etc/xdg/autostart/gnome-keyring-secrets.desktop']' can't be converted to File object(s).
This will become a hard error in the future.
session/meson.build:153: WARNING: Custom target input '['/etc/xdg/autostart/gnome-keyring-ssh.desktop']' can't be converted to File object(s).
This will become a hard error in the future.
Build targets in project: 19

elementary-session-settings 5.0.3

  User defined options
    Native files           : /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/temp/meson.x86_64-pc-linux-gnu.amd64.ini
    build.pkg_config_path  : /usr/share/pkgconfig
    buildtype              : plain
    libdir                 : lib64
    localstatedir          : /var/lib
    pkg_config_path        : /usr/share/pkgconfig
    prefix                 : /usr
    sysconfdir             : /etc
    wrap_mode              : nodownload
    accessibility          : false
    detect-program-prefixes: false

Found ninja-1.10.2 at /usr/bin/ninja
>>> Source configured.
>>> Compiling source in /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/session-settings-6.0.0 ...
meson compile -C /var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/pantheon-shell-6.0.0-build --jobs 6 --load-average 0 --verbose
ninja: Entering directory `/var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/pantheon-shell-6.0.0-build'
ninja: error: '/etc/xdg/autostart/gnome-keyring-pkcs11.desktop', needed by 'session/pantheon-gnome-keyring-pkcs11.desktop', missing and no known rule to make it
 * ERROR: pantheon-base/pantheon-shell-6.0.0::elementary failed (compile phase):
 *   compile failed
 *
 * Call stack:
 *     ebuild.sh, line  127:  Called src_compile
 *   environment, line 2242:  Called meson_src_compile
 *   environment, line 1584:  Called die
 * The specific snippet of code:
 *       "$@" || die "compile failed"
 *
 * If you need support, post the output of `emerge --info '=pantheon-base/pantheon-shell-6.0.0::elementary'`,
 * the complete build log and the output of `emerge -pqv '=pantheon-base/pantheon-shell-6.0.0::elementary'`.
 * The complete build log is located at '/var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/temp/environment'.
 * Working directory: '/var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/session-settings-6.0.0'
 * S: '/var/tmp/portage/pantheon-base/pantheon-shell-6.0.0/work/session-settings-6.0.0'

**Comment by pimvullers** [comment]
Pushed some updates. Please check if this resolves your issue.

**Comment by pimvullers** [comment]
Re-open if problem still exists.
