### ISSUE TITLE
Missing dependency for pantheon-files + failure afterwards

### ISSUE THREAD

**Issue by RetronEletron** [pimvullers/elementary#223]
Run-time dependency libgit2-glib-1.0 found: NO (tried pkgconfig and cmake)
Solution:
emerge libgit2-glib

**Comment by RetronEletron** [comment]
I reinstall from time to time and use ~amd64 hence why the issues with meson for example and some other stuff

**Comment by pimvullers** [comment]
Currently busy to fix all packages for meson, there are various. Expect an update in 1-2 hours.

**Comment by RetronEletron** [comment]
I'll keep it open for now as the issue is still here by default
