### ISSUE TITLE
gala fails to compile with mutter 42

### ISSUE THREAD

**Issue by RetronEletron** [pimvullers/elementary#224]
libmutter errors than failure works with mutter 41

**Comment by RetronEletron** [comment]
yes more issues lol take your time

**Comment by RetronEletron** [comment]
Ok now all of it managed to compile.

What is needed to get fixed:

Mutter 42 Support
meson-0.61.4-r2 Support
add in libgit2-glib for pantheon-files and libcloudproviders to be build with the vala flag.

**Comment by pimvullers** [comment]
yes, since ubuntu is usually late with this, and elementary is on LTS releases they are generally quite behind on recent gnome packages. Let me check upstream if there is anything

**Comment by pimvullers** [comment]
You compiled gala by downgrading mutter? Or which other fix did you apply?

I just tried adding the upstream patch, but that breaks the build on my side (so probably I need some other patches as well, need to check which ones).

**Comment by RetronEletron** [comment]
I compiled gala by downgrading mutter correct

**Comment by pimvullers** [comment]
> What is needed to get fixed:
> 
> Mutter 42 Support 
> meson-0.61.4-r2 Support 
> add in libgit2-glib for pantheon-files and libcloudproviders to be build with the vala flag.

These should all be solved now. Please validate and re-open if it still isn't working (I don't want to break my system by updating to mutter42). Meson I did upgrade and validate for all packages that I had installed from this overlay.
