### ISSUE TITLE
Circular dependencies with pulseaudio

### ISSUE THREAD

**Issue by ThomasBeckham** [pimvullers/elementary#228]
Error: circular dependencies:

(media-libs/libpulse-16.1:0/0::gentoo, ebuild scheduled for merge) depends on (media-libs/libsndfile-1.1.0-r1:0/0::gentoo, ebuild scheduled for merge) (buildtime) 
(media-sound/mpg123-1.30.0:0/0::gentoo, ebuild scheduled for merge) (buildtime_slot_op) 
(media-sound/pulseaudio-16.0:0/0::gentoo, ebuild scheduled for merge) (buildtime) 
(media-libs/libpulse-16.1:0/0::gentoo, ebuild scheduled for merge) (buildtime)

**Comment by pimvullers** [comment]
This is not an elementary overlay issue.
To break the dependency first emerge pulseaudio without sndfile useflag (or sndfile without pulseaudio flag), then merge again with the desired flag.

**Comment by ThomasBeckham** [comment]
Thank you
