### ISSUE TITLE
switchboard-plug-onlineaccounts failed in compile phase

### ISSUE THREAD

**Issue by KaltWulx** [pimvullers/elementary#230]
Hi, first I want to say thank you to every body for your work :)

I'm trying to install pantheon-meta, and I get this error:
[build.txt](https://github.com/pimvullers/elementary/files/10223014/build.txt)

This is my emerge info output: 
[emerge-info.txt](https://github.com/pimvullers/elementary/files/10223016/emerge-info.txt)

I don't know where to go from here... :/

**Comment by pimvullers** [comment]
Which version of gnome-extra/evolution-data-server do you have installed?

**Comment by KaltWulx** [comment]
Hi, the version 3.46.2

`gnome-extra/evolution-data-server-3.46.2:0/64-11-21-4-2-27-2-27-4-0::gentoo  USE="gnome-online-accounts gtk introspection vala weather -berkdb -gtk-doc -kerberos -ldap -oauth -test" 0 KiB
`

**Comment by pimvullers** [comment]
Would it be possible (for an experiment) to downgrade to 3.44, to see if it resolves it (otherwise I will try to upgrade that package to reproduce).

**Comment by KaltWulx** [comment]
Sorry, I was trying, but I can't do it. Slot conflicts and graph dependencies, :/ I can't figure out how to resolve it.
`sudo emerge -pv  gnome-extra/evolution-data-server

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  NS    ] sci-geosciences/geocode-glib-3.26.4-r1:0::gentoo [3.26.4-r201:2::gentoo] USE="introspection -gtk-doc -test" 0 KiB
[ebuild     UD ] dev-libs/libgweather-4.0.0-r1:4/4-0::gentoo [4.2.0:4/4-0::gentoo] USE="introspection vala -gtk-doc -test" 0 KiB
[ebuild  N     ] dev-libs/libgdata-0.18.1-r1:0/22::gentoo  USE="crypt gnome-online-accounts introspection vala -gtk-doc -test" 832 KiB
[ebuild  N     ] gnome-extra/evolution-data-server-3.44.4-r2:0/63-26-20::local  USE="gnome-online-accounts gtk introspection ipv6 vala weather -berkdb -gtk-doc -kerberos -ldap -oauth -test" 4 673 KiB

Total: 4 packages (1 downgrade, 2 new, 1 in new slot), Size of downloads: 5 504 KiB

!!! Multiple package instances within a single package slot have been pulled
!!! into the dependency graph, resulting in a slot conflict:

dev-libs/libgweather:4

  (dev-libs/libgweather-4.0.0-r1:4/4-0::gentoo, ebuild scheduled for merge) USE="introspection vala -gtk-doc -test" ABI_X86="(64)" pulled in by
    <dev-libs/libgweather-4.2.0:4= required by (gnome-extra/evolution-data-server-3.44.4-r2:0/63-26-20::local, ebuild scheduled for merge) USE="gnome-online-accounts gtk introspection ipv6 vala weather -berkdb -gtk-doc -kerberos -ldap -oauth -test" ABI_X86="(64)"
    ^                     ^^^^^^^^                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

  (dev-libs/libgweather-4.2.0:4/4-0::gentoo, installed) USE="introspection vala -gtk-doc -test" ABI_X86="(64)" pulled in by
    >=dev-libs/libgweather-4.2.0:4= required by (gnome-base/gnome-settings-daemon-43.0:0/0::gentoo, installed) USE="colord cups elogind networkmanager wayland -debug -modemmanager -smartcard -systemd (-test)" ABI_X86="(64)" INPUT_DEVICES="-wacom"
    ^^                     ^^^^^^^^                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    (and 1 more with the same problem)

NOTE: Use the '--verbose-conflicts' option to display parents omitted above

It may be possible to solve this problem by using package.mask to
prevent one of those packages from being selected. However, it is also
possible that conflicting dependencies exist such that they are
impossible to satisfy simultaneously.  If such a conflict exists in
the dependencies of two different packages, then those packages can
not be installed simultaneously. You may want to try a larger value of
the --backtrack option, such as --backtrack=30, in order to see if
that will solve this conflict automatically.

For more information, see MASKED PACKAGES section in the emerge man
page or refer to the Gentoo Handbook.
`

**Comment by pimvullers** [comment]
I just pushed an update which adds a patch from a pull request from the upstream project. This should hopefully solve the build issue.

**Comment by KaltWulx** [comment]
Yeah! It works!

> kalt@wulx-laptop /var/db/repos/gentoo/gnome-extra/evolution-data-server $ sudo emerge -aq pantheon-meta
[ebuild  N    ] gnome-extra/evolution-data-server-3.46.2 
[ebuild  N    ] pantheon-base/switchboard-plug-onlineaccounts-6.5.1-r1 
[ebuild  N    ] pantheon-base/pantheon-meta-6.0.0-r1 

Would you like to merge these packages? [Yes/No] y
>>> Verifying ebuild manifests
>>> Emerging (1 of 3) gnome-extra/evolution-data-server-3.46.2::gentoo
>>> Installing (1 of 3) gnome-extra/evolution-data-server-3.46.2::gentoo
>>> Emerging (2 of 3) pantheon-base/switchboard-plug-onlineaccounts-6.5.1-r1::elementary
>>> Installing (2 of 3) pantheon-base/switchboard-plug-onlineaccounts-6.5.1-r1::elementary
>>> Emerging (3 of 3) pantheon-base/pantheon-meta-6.0.0-r1::elementary
>>> Installing (3 of 3) pantheon-base/pantheon-meta-6.0.0-r1::elementary
>>> Recording pantheon-base/pantheon-meta in "world" favorites file...

 * IMPORTANT: 4 config files in '/etc' need updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.
kalt@wulx-laptop /var/db/repos/gentoo/gnome-extra/evolution-data-server $ 


Thank you!

**Comment by pimvullers** [comment]
Given #231 I might need to make some modifications.
