### ISSUE TITLE
pantheon photos "geocode-glib-1.0" not found

### ISSUE THREAD

**Issue by bhilldev** [pimvullers/elementary#233]
The version of geocode-glib version isn't specified in the ebuild file, so it's possibly defaulting to looking for 1.0.

Same issue that calendars had I guess.

**Comment by pimvullers** [comment]
Proper update to also support newer geocode-glib would depend on https://github.com/elementary/photos/issues/718

**Comment by pimvullers** [comment]
Added patch from upstream to fix build. Cleaned up dependencies for other packages related to geocode/rest/soup/webkit.
