### ISSUE TITLE
dev-libs/libcloudproviders-0.3.1::elementary

### ISSUE THREAD

**Issue by tsaotse** [pimvullers/elementary#235]
dev-libs/libcloudproviders-0.3.1::elementary
net-libs/libcloudproviders-0.3.1::gentoo
duplicated

>>> Completed installing dev-libs/libcloudproviders-0.3.1 into /var/tmp/portage/dev-libs/libcloudproviders-0.3.1/image

 * Final size of build directory: 1400 KiB (1.3 MiB)
 * Final size of installed tree:   436 KiB

strip: x86_64-pc-linux-gnu-strip --strip-unneeded -N __gentoo_check_ldflags__ -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   /usr/lib64/libcloudproviders.so.0.3.1
>>> Done.
 * checking 17 files for package collisions
 * This package will overwrite one or more files that may belong to other
 * packages (see list below). You can use a command such as `portageq
 * owners / <filename>` to identify the installed package that owns a
 * file. If portageq reports that only one package owns a file then do
 * NOT file a bug report. A bug report is only useful if it identifies at
 * least two or more packages that are known to install the same file(s).
 * If a collision occurs and you can not explain where the file came from
 * then you should simply ignore the collision since there is not enough
 * information to determine if a real problem exists. Please do NOT file
 * a bug report at https://bugs.gentoo.org/ unless you report exactly
 * which two packages install the same file(s). See
 * https://wiki.gentoo.org/wiki/Knowledge_Base:Blockers for tips on how
 * to solve the problem. And once again, please do NOT file a bug report
 * unless you have completely understood the above message.
 * 
 * Detected file collision(s):
 * 
 * 	/usr/include/cloudproviders/cloudproviders.h
 * 	/usr/include/cloudproviders/enums.h
 * 	/usr/include/cloudproviders/cloudprovidersproviderexporter.h
 * 	/usr/include/cloudproviders/cloudproviderscollector.h
 * 	/usr/include/cloudproviders/cloudprovidersprovider.h
 * 	/usr/include/cloudproviders/cloudprovidersaccount.h
 * 	/usr/include/cloudproviders/cloudprovidersaccountexporter.h
 * 	/usr/lib64/libcloudproviders.so.0.3.1
 * 	/usr/lib64/girepository-1.0/CloudProviders-0.3.typelib
 * 	/usr/lib64/pkgconfig/cloudproviders.pc
 * 	/usr/share/gir-1.0/CloudProviders-0.3.gir
 * 	/usr/share/doc/libcloudproviders-0.3.1/CHANGELOG.bz2
 * 	/usr/share/doc/libcloudproviders-0.3.1/README.md.bz2
 * 	/usr/lib64/libcloudproviders.so
 * 	/usr/lib64/libcloudproviders.so.0
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * net-libs/libcloudproviders-0.3.1:0::gentoo
 * 	/usr/include/cloudproviders/cloudproviders.h
 * 	/usr/include/cloudproviders/cloudprovidersaccount.h
 * 	/usr/include/cloudproviders/cloudprovidersaccountexporter.h
 * 	/usr/include/cloudproviders/cloudproviderscollector.h
 * 	/usr/include/cloudproviders/cloudprovidersprovider.h
 * 	/usr/include/cloudproviders/cloudprovidersproviderexporter.h
 * 	/usr/include/cloudproviders/enums.h
 * 	/usr/lib64/girepository-1.0/CloudProviders-0.3.typelib
 * 	/usr/lib64/libcloudproviders.so
 * 	/usr/lib64/libcloudproviders.so.0
 * 	/usr/lib64/libcloudproviders.so.0.3.1
 * 	/usr/lib64/pkgconfig/cloudproviders.pc
 * 	/usr/share/doc/libcloudproviders-0.3.1/CHANGELOG.bz2
 * 	/usr/share/doc/libcloudproviders-0.3.1/README.md.bz2
 * 	/usr/share/gir-1.0/CloudProviders-0.3.gir
 * 
 * Package 'dev-libs/libcloudproviders-0.3.1' NOT merged due to file
 * collisions. If necessary, refer to your elog messages for the whole
 * content of the above message.

**Comment by pimvullers** [comment]
Thanks for reporting. Do you know which package is pulling in the Gentoo version (just out of curiosity).

I will review the Gentoo one to see if it can be used, otherwise I will anyhow move it to the same category.
