### ISSUE TITLE
sys-apps/xdg-desktop-portal-pantheon-7.1.1 requires granite-7

### ISSUE THREAD

**Issue by luna-xenia** [pimvullers/elementary#244]
Looks like sys-apps/xdg-desktop-portal-pantheon needs granite-7 which isn't yet in the gentoo repos, seems like my build is pulling the version from there instead of this repo:

```
Found CMake: /usr/bin/cmake (3.26.5)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency granite-7 found: NO (tried pkgconfig and cmake)

meson.build:15:14: ERROR: Dependency "granite-7" not found, tried pkgconfig and 
cmake
```

Sorry for the bad build log, I can get better ones later if needed but I'm building in catalyst for now

**Comment by slipdip123** [comment]
FWIW, I managed to get around this by editing the xdg-desktop-portal-pantheon ebuild to require version 7.3.0 or above

**Comment by pimvullers** [comment]
Thanks for reporting, I corrected the dependencies now.
