### ISSUE TITLE
wingpanel-sound-indicator crashes wingpanel when hover or clicked upon.

### ISSUE THREAD

**Issue by lukashebda** [pimvullers/elementary#245]
[12544.766057] io.elementary.w[3159]: segfault at 38 ip 00007f5c87923c21 sp 00007ffc1746e620 error 4 in libsound.so[7f5c87917000+25000] likely on CPU 2 (core 2, socket 0)

I suspect it's related to issue in upstream:
https://github.com/elementary/wingpanel-indicator-sound/issues/99

Wingpanel crashes when pantheon-music or other player is absent:
Will check if presence of vlc and pantheon-music fixes the issue.

We could add vlc or music as a dependency.

**Comment by pimvullers** [comment]
I will check how much effort it is to have the not null check in the code, to avoid unnecessary dependencies.

**Comment by pimvullers** [comment]
Can you provide some guidance how to reproduce? I uninstalled music, videos and vlc, no crash on my side.

**Comment by pimvullers** [comment]
[default_player_not_null.patch.txt](https://github.com/pimvullers/elementary/files/13400323/default_player_not_null.patch.txt)
If you can reproduce, then you can also try this patch using the user patch mechanism: https://wiki.gentoo.org/wiki//etc/portage/patches
If it works, I can include it in the ebuild.

**Comment by lukashebda** [comment]
Ask you asked I uninstalled vlc and was able to reproduce the crash. The patch provided for you fixes the issue.
For future references: The patch must have .patch or .diff extention to be able to be recognised by portage.

**Comment by pimvullers** [comment]
Thanks for confirmation, i will include it in the ebuild, and submit upstream. But only next weekend, as i am currently on a business trip.

Had to use .txt as GitHub die not accept .patch for attachments.
