### ISSUE TITLE
pantheon-base/pantheon-files fails to build due to dev-util/meson change to dev-build/meson

### ISSUE THREAD

**Issue by p4r4D0xum** [pimvullers/elementary#246]
emerge: there are no ebuilds to satisfy ">=dev-util/meson-0.50.0".
(dependency required by "pantheon-base/pantheon-files-6.5.3::elementary" [ebuild])
(dependency required by "pantheon-files" [argument])

**Comment by pimvullers** [comment]
Fixed in 2e441e847962f18b88f1fb38c654f0f7dde934e1 dropped it instead, as it is already covered by the eclass.
