### ISSUE TITLE
x11-wm/gala-71.3 crashes after login with x11-wm/mutter -wayland

### ISSUE THREAD

**Issue by p4r4D0xum** [pimvullers/elementary#248]
I couldn't get pantheon running after fresh install.

dmesg shows:
 io.elementary.g[2487]: segfault at 7fc2d0387370 ip 00007fc2d0387370 sp 00007fffa64f7558 error 14 in libgcc_s.so.1[7fc2d0473000+4000] likely on CPU 2 (core 2, socket 0)

after a while I noticed that mutter is without wayland flag and it solved the issue.

mutter wayland pulled x11-base/wayland with libei flag for some reason, checked on other host libei disabled.

**Comment by pimvullers** [comment]
Can you elaborate which mutter version you are using?

I indeed have mutter with wayland USE flag, as I'm looking into state of wayland support for pantheon. 
However, would prefer to avoid a hard dependency on wayland...

**Comment by p4r4D0xum** [comment]
x11-wm/mutter-45.2-r1 USE="elogind introspection udev wayland" and VIDEO_CARDS="-nvidia".
I hope this suffice.

**Comment by pimvullers** [comment]
Thanks, that matches what I have... and before you had it without wayland USE flag, correct? Any other differences?

**Comment by pimvullers** [comment]
Looked a bit, and there is already a wayland dependency for gtk in pantheon-files, so decided to just add the dependency.

**Comment by p4r4D0xum** [comment]
> Thanks, that matches what I have... and before you had it without wayland USE flag, correct? Any other differences?

Indeed, without wayland flag, everthing compiled fine, but gala kept crashing.
