### ISSUE TITLE
pantheon-base/switchboard-plug-about-6.2.0 fails to build.

### ISSUE THREAD

**Issue by p4r4D0xum** [pimvullers/elementary#249]
[build.log](https://github.com/pimvullers/elementary/files/14538046/build.log)
[emerge_info.log](https://github.com/pimvullers/elementary/files/14538050/emerge_info.log)

an appstream issue?

**Comment by pimvullers** [comment]
I've synced appstream with gentoo repo. I expect you have ~amd64, which now pulled in 1.0.1. If it works after this update I will also update the dependency in the package to map to <1.0.0, so please confirm.
