### ISSUE TITLE
pantheon-extra/pantheon-agent-polkit-8.0.0 pulled by pantheon-base/pantheon-shell-6.0.0-r1 requires gui-libs/libadwaita

### ISSUE THREAD

**Issue by p4r4D0xum** [pimvullers/elementary#253]
The Meson build system
Version: 1.4.0
Source dir: /var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/work/pantheon-agent-polkit-8.0.0
Build dir: /var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/work/pantheon-agent-polkit-8.0.0-build
Build type: native build
Project name: io.elementary.desktop.agent-polkit
Project version: 8.0.0
C compiler for the host machine: x86_64-pc-linux-gnu-gcc (gcc 13.2.1 "x86_64-pc-linux-gnu-gcc (Gentoo 13.2.1_p20240210 p14) 13.2.1 20240210")
C linker for the host machine: x86_64-pc-linux-gnu-gcc ld.bfd 2.41
Vala compiler for the host machine: /usr/bin/valac-0.56 (valac 0.56.16)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/x86_64-pc-linux-gnu-pkg-config) 2.2.0
Found CMake: /usr/bin/cmake (3.28.5)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libadwaita-1 found: NO (tried pkgconfig and cmake)

meson.build:19:8: ERROR: Dependency "libadwaita-1" not found, tried pkgconfig and cmake

A full log can be found at /var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/work/pantheon-agent-polkit-8.0.0-build/meson-logs/meson-log.txt
 * ERROR: pantheon-extra/pantheon-agent-polkit-8.0.0::elementary failed (configure phase):
 *   configure failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 2774:  Called meson_src_configure
 *   environment, line 2050:  Called die
 * The specific snippet of code:
 *       [[ ${rv} -eq 0 ]] || die -n "configure failed";
 * 
 * If you need support, post the output of `emerge --info '=pantheon-extra/pantheon-agent-polkit-8.0.0::elementary'`,
 * the complete build log and the output of `emerge -pqv '=pantheon-extra/pantheon-agent-polkit-8.0.0::elementary'`.
 * The complete build log is located at '/var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/temp/environment'.
 * Working directory: '/var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/work/pantheon-agent-polkit-8.0.0'
 * S: '/var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/work/pantheon-agent-polkit-8.0.0'

>>> Failed to emerge pantheon-extra/pantheon-agent-polkit-8.0.0, Log file:

>>>  '/var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/temp/build.log'

 * Messages for package pantheon-extra/pantheon-agent-polkit-8.0.0:

 * ERROR: pantheon-extra/pantheon-agent-polkit-8.0.0::elementary failed (configure phase):
 *   configure failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 2774:  Called meson_src_configure
 *   environment, line 2050:  Called die
 * The specific snippet of code:
 *       [[ ${rv} -eq 0 ]] || die -n "configure failed";
 * 
 * If you need support, post the output of `emerge --info '=pantheon-extra/pantheon-agent-polkit-8.0.0::elementary'`,
 * the complete build log and the output of `emerge -pqv '=pantheon-extra/pantheon-agent-polkit-8.0.0::elementary'`.
 * The complete build log is located at '/var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/temp/environment'.
 * Working directory: '/var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/work/pantheon-agent-polkit-8.0.0'
 * S: '/var/tmp/portage/pantheon-extra/pantheon-agent-polkit-8.0.0/work/pantheon-agent-polkit-8.0.0'

installing libadwaita fixes build crash. Tested on gui-libs/libadwaita-1.4.4.

**Comment by nater1983** [comment]
I can confirm that installing libadwaita fix's the build crash

**Comment by pimvullers** [comment]
adwaita dep added
