### ISSUE TITLE
pantheon-base/switchboard-6.0.2-r1 file collision.

### ISSUE THREAD

**Issue by p4r4D0xum** [pimvullers/elementary#255]
[U?] pantheon-base/switchboard [1]
     Available versions:  
     (2)    6.0.2-r1
     (3)    8.0.0
       {examples}
     Installed versions:  6.0.2(11:16:05 PM 09/06/2023)(-examples)
     Homepage:            https://github.com/elementary/switchboard
     Description:         Modular desktop settings hub

Unmerging the 6.0.2 version solves the problem.
[switchboard-6.0.2-r1_file_collision.txt](https://github.com/user-attachments/files/16069546/switchboard-6.0.2-r1_file_collision.txt)

**Comment by pimvullers** [comment]
OK, seems like you hit some odd situation (I guess by manually updating individual packages) where SLOT 0 version was still present from an earlier install, and emerge did not properly see it as an update. Added a blocker on SLOT 0 now to prevent the conflict.
