### ISSUE TITLE
dev-libs/granite-7.5.0 build failure with USE=doc

### ISSUE THREAD

**Issue by leonchik1976** [pimvullers/elementary#257]
Program valadoc found: NO

doc/meson.build:1:10: ERROR: Program 'valadoc' not found or not executable
[build.log](https://github.com/user-attachments/files/17841401/build.log)
[emerge_info.txt](https://github.com/user-attachments/files/17841416/emerge_info.txt)

**Comment by pimvullers** [comment]
Dropped doc use flag. I managed to fix the document generation, but the meson build scripts don't install the docs, so they have no added value just to build them.
